### PR TITLE
Attach child error messages to ensure-indexes error

### PR DESCRIPTION
**Pull request by EpicWink**

### CODE REVIEW

**Comment by EpicWink** [comment]
TODO:
* [ ] Add test
* [ ] Run tests
* [ ] Reformat commit messages and PR description

**Comment by B4nan** [comment]
Do you plan to work on this?

**Comment by EpicWink** [comment]
Yes, sorry. I have been busy with life. I foresee free time in my future

**Comment by EpicWink** [comment]
I'm having trouble with the tests, I think I'm misunderstanding how Jest patches things

**Pull request closed without merging**
