### PR TITLE
test(core): verify findAndCount for inverse relations

### PR DESCRIPTION
**Pull request by followben**
Demonstrates #858.

### CODE REVIEW

**Comment by followben** [comment]
Ive been looking into root cause with a view to adding a fix.

So qb in `AbstractSqlDriver.count()` doesn't actually generate a count statement all. This is the statement it produces:

```sql
select distinct
    "e0"."id",
    "e2"."id" as "voucher_id",
    "e4"."id" as "voucher_id"
from "transaction" as "e0"
left join "account" as "e1" on "e0"."credit_account_id" = "e1"."id"
left join "voucher" as "e2" on "e1"."id" = "e2"."account_id"
left join "account" as "e3" on "e0"."debit_account_id" = "e3"."id"
left join "voucher" as "e4" on "e3"."id" = "e4"."account_id"
where ("e2"."id" = $1 or "e4"."id" = $2)
```

That looks correct in terms of joins and the where, but because or aliases both have the same name, the value returned in that column (`"voucher_id"` in this case) can intermittently be null depending on the run.

Given the statement is identical to that generated by the qb in `AbstractSqlDriver.find()`, I wonder if this isn't a wider problem?

**Comment by B4nan** [comment]
That sounds very improbable, `driver.count()` is literally creating QB in count mode. I guess you are just observing it wrongly, those queries are fired in parallel...

Better to debug just the `em.count()` part, as `findAndCount()` is as simple as running `find()` and `count()`:

image

**Comment by followben** [comment]
Yup, I'm calling `qb.getQuery()` on the qbs in `AbstractSqlDriver.count()` and `AbstractSqlDriver.find()` (specifically just prior to the execution of [L171](https://github.com/mikro-orm/mikro-orm/blob/9799e70bd7235695f4f1e55b25fe61bbc158eb38/packages/knex/src/AbstractSqlDriver.ts#L171) and [L60](https://github.com/mikro-orm/mikro-orm/blob/9799e70bd7235695f4f1e55b25fe61bbc158eb38/packages/knex/src/AbstractSqlDriver.ts#L60) respectively).

They're almost exactly the same except the latter selects all cols from the primary entity, and while the former just selects the id.

**Comment by B4nan** [comment]
Hmm if so, then the issue must be with resetting the qb type to `select` probably in the `CriteriaNode` where autojoining happens. 

My guess is that `qb.addSelect()` is called on the count qb instance, which should be ignored if the qb is in select mode (I'd say it's ok to keep the `addSelect` call, but inside that method we should check if the type is `select`, if not, ignore).

**Comment by B4nan** [comment]
It's indeed caused by the `qb.addSelect`, fixed that already via 9b8056c7.

The other thing with dual `voucher_id` alias should not really matter, in fact this bit should not be part of the query at all. Will deal with that too, it looks confusing, but the query should select only props from the root entity - the transaction - and that entity do not have a `voucher` property (this clause is used for selecting 1:1 owner when querying from the inverse side, but that happens one level deeper).

**Comment by B4nan** [comment]
The latter is now fixed via 86c3032, the auto-select is now happening only for root entity.

Added the tests only at the query builder level to make them fast as possible (as well as truly minimal).

Thanks for the repro, helped a lot!

**Pull request closed without merging**
