### PR TITLE
chore: fix commit message conventions link in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by MatthiasKunnen**

### CODE REVIEW

**Comment by B4nan** [comment]
May I know where is this linked from (the broken link)? Have you verified it was not referenced from other places with the currently available id?

**Comment by MatthiasKunnen** [comment]
It's referenced in the same file, here:
https://github.com/mikro-orm/mikro-orm/blob/227d5bce61e1e4259763fc849ab4c42200fd6bca/CONTRIBUTING.md#L64

**Comment by B4nan** [comment]
Maybe it would be better to fix the link instead of changing the id?

**Comment by MatthiasKunnen** [comment]
Will do. I just thought based on other links in the file and project that the anchor tag was the preferred approach.

**Comment by B4nan** [comment]
Not sure, it probably does not matter much, but fixing links sounds like safer approach in general.

**Pull request merged**
