### PR TITLE
docs: fix typo

### PR DESCRIPTION
**Pull request by PlatinBae**

### CODE REVIEW

**Comment by B4nan** [comment]
Thanks! Can you please remove the permission changes (`100755 → 100644`)?

**Comment by PlatinBae** [comment]
Should I change the permission from 100644 to 100755 again?

**Comment by B4nan** [comment]
Yes, the diff should be clean, containing only the files you actually changed. You could also soft reset the commit, add only the files you changed, and force push the result. Changing the permissions back explicitly will probably do the trick too.

**Comment by B4nan** [comment]
Perfect, thanks!

**Review by B4nan — APPROVED** [review]

**Pull request merged**
