### PR TITLE
fix(schema): resolve missing auto_increment for PK in `MySQL/MariaDB` update DDL

### LINKED ISSUE #6072: Missing auto_increment in Update DDL for primary key changes in MySQL..
### Describe the bug

1. Modify primary key properties of existing entity.
2. Generate update DDL using the schema generator.
3. Generated alterDDL is missing auto_increment.

### Reproduction

https://github.com/lsh4711/reproduction

### What driver are you using?

@mikro-orm/mysql

### MikroORM version

next(after PR#6065)

### Node.js version

20.17.0

### Operating system

Windows 11

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Discord](https://discord.gg/w8bjxFHS7X).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by lsh4711**
Closes #6072

### CODE REVIEW

**Comment by B4nan** [comment]
I can't wait for the time when we get rid of knex in there, the code is so convoluted because of their weird `increments/bigIncrements` abstraction. I hope this wont break anything...

**Comment by lsh4711** [comment]
It seems that issues arise from knex's inflexible `increments` abstraction, making it difficult to fix externally...
I will study more to resolve other issues as well.
I hope to continue contributing to this great project!
Specifically, I want to make the schema generator more robust. :)

**Comment by B4nan** [comment]
Ok, I would like to see knex gradually removed from pretty much everywhere, so if you see more issues like this, consider doing it right ahead instead of hacking your way with knex. If its a one-liner to fix with the current abstractions, let's do that, but if you need more control and you see it's gonna be more about fighting knex, it's often better to just get around it completely. 

I hope we could get rid of knex in v7 (and let users pick whatever QB they want to from outside).

**Comment by lsh4711** [comment]
Got it.
I will look into Knex in more detail and work towards gradually replacing it if possible.
I also think about abstraction for external query builders.
Thank you! :)

**Comment by B4nan** [comment]
> I also think about abstraction for external query builders.

Note that this is only for runtime, we don't need it internally for schema queries. No need to worry about that, now we just need to get rid of the tight coupling, the goal is to use knex only as a query runner first, which can be done in a non breaking way.

**Comment by lsh4711** [comment]
Well noted with thanks.
I also hope for the day we are free from Knex!

**Pull request merged**
