### PR TITLE
chore: add prepublish hook

### PR DESCRIPTION
**Pull request by kibertoad**
refs #527

### CODE REVIEW

**Comment by B4nan** [comment]
This needs to go to `dev` brach. Please fix the conflicts.

**Comment by kibertoad** [comment]
@B4nan https://github.com/lerna/lerna/issues/1169
Looks like it needs to be inside each separate package. Should I move it there?

**Comment by B4nan** [comment]
Not sure what is the best practice with lerna. I remember I read somewhere I still need to run `lerna build` manually before publishing, but it looks like `lerna publish` does traverse the packages in the correct order anyway, so having `prepublish` script inside the packages should work just fine and we could skip the manual `lerna build` call. We already check whether all packages are buildable, so it should be safe to do it like this when publishing.

**Comment by kibertoad** [comment]
@B4nan Done.

**Comment by B4nan** [comment]
Thanks!

**Pull request merged**
