### PR TITLE
fix(mssql): fix creating migrations due to a missing helper method

### LINKED ISSUE #5633: Not able to run migrations in MS SQL Server
### Describe the bug

I am trying to run the migration file generated for using the migration up command. It runs into an error
```
Error: createSchema is not supported for this dialect (only PostgreSQL supports it currently).
    at throwOnlyPGError (C:\project\node_modules\.pnpm\knex@3.1.0_pg@8.11.5_tedious@18.2.0\node_modules\knex\lib\schema\compiler.js:182:9)
    at SchemaCompiler_MSSQL.createSchema (C:\project\node_modules\.pnpm\knex@3.1.0_pg@8.11.5_tedious@18.2.0\node_modules\knex\lib\schema\compiler.js:25:5)
    at SchemaCompiler_MSSQL.toSQL (C:\project\node_modules\.pnpm\knex@3.1.0_pg@8.11.5_tedious@18.2.0\node_modules\knex\lib\schema\compiler.js:97:26)
    at SchemaBuilder.toSQL (C:\project\node_modules\.pnpm\knex@3.1.0_pg@8.11.5_tedious@18.2.0\node_modules\knex\lib\schema\builder.js:36:51)
    at ensureConnectionCallback (C:\project\node_modules\.pnpm\knex@3.1.0_pg@8.11.5_tedious@18.2.0\node_modules\knex\lib\execution\internal\ensure-connection-callback.js:4:30)
    at Runner.ensureConnection (C:\project\node_modules\.pnpm\knex@3.1.0_pg@8.11.5_tedious@18.2.0\node_modules\knex\lib\execution\runner.js:318:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Runner.run (C:\project\node_modules\.pnpm\knex@3.1.0_pg@8.11.5_tedious@18.2.0\node_modules\knex\lib\execution\runner.js:30:19)
    at async MigrationStorage.ensureTable (C:\project\node_modules\.pnpm\@mikro-orm+migrations@6.2.8_@mikro-orm+core@6.2.8_@types+node@18.15.11_pg@8.11.5\node_modules\@mikro-orm\migrations\MigrationStorage.js:81:13)
    at async Migrator.ensureDatabase (C:\project\node_modules\.pnpm\@mikro-orm+migrations@6.2.8_@mikro-orm+core@6.2.8_@types+node@18.15.11_pg@8.11.5\node_modules\@mikro-orm\migrations\Migrator.js:173:9)
```

## How to Reproduce

1) Create an Azure SQL server resource and a database
2) Using the MSSQL driver present in version 6.2.8, we have use the following mikroorm configuration in a nest js application.
```ts
import { LoadStrategy, Platform } from '@mikro-orm/core';
import { Migrator } from '@mikro-orm/migrations';
import {
  MsSqlDriver,
  defineConfig,
  StringType,
  Type,
  ArrayType,
} from '@mikro-orm/mssql';
import { TsMorphMetadataProvider } from '@mikro-orm/reflection';
import { SeedManager } from '@mikro-orm/seeder';
import { SqlHighlighter } from '@mikro-orm/sql-highlighter';
import { Logger, NotFoundException } from '@nestjs/common';
import 'dotenv/config';

const logger = new Logger('MikroORM');

// const isPortfolio = process.env.NODE_ENV === 'portfolio';

const config = defineConfig({
  entities: ['dist/backend/**/*.entity.js'],
  entitiesTs: ['src/**/*.entity.ts'],
  driver: MsSqlDriver,
  loadStrategy: LoadStrategy.JOINED,
  dbName: process.env['MSSQL_DBNAME'] as string,
  host: process.env['MSSQL_DBHOST'] as string,
  password: process.env['MSSQL_DBPASSWORD'] as string,
  user: process.env['MSSQL_DBUSERNAME'] as string,
  port: parseInt(process.env['MSSQL_DBPORT'] || '1433', 10),
  highlighter: new SqlHighlighter(),
  driverOptions: {
    connection: {
      database: process.env['MSSQL_DBNAME'] as string,
      userName: process.env['MSSQL_DBUSERNAME'] as string,
      password: process.env['MSSQL_DBPASSWORD'] as string,
      encrypt: true,
      trustServerCertificate: true,
      port: parseInt(process.env['MSSQL_DBPORT'] || '1433', 10),
    },
  },
  debug: true,
  logger: logger.log.bind(logger),
  metadataProvider: TsMorphMetadataProvider,
  allowGlobalContext: true,
  discovery: {
    getMappedType(type: string, platform: Platform) {
      // override the mapping for string properties only
      if (type === 'enum') {
        return Type.getType(StringType);
      }
      if (type === 'string') {
        return Type.getType(StringType);
      }
      if (type === 'enumArray') {
        return Type.getType(ArrayType);
      }

      return platform.getDefaultMappedType(type);
    },
  },
  migrations: {
    tableName: 'mikro_orm_migrations',
    path: './migrations',
    glob: '!(*.d).{js,ts}',
    transactional: true,
    disableForeignKeys: true,
    allOrNothing: true,
    dropTables: false,
    safe: true,
    emit: 'ts', // migration generation mode
  },
  schemaGenerator: {
    disableForeignKeys: true,
    createForeignKeyConstraints: false,
  },
  seeder: {
    path: './dist/backend/seeders',
    pathTs: './seeders',
    defaultSeeder: 'DatabaseSeeder',
    glob: '!(*.d).{js,ts}',
    emit: 'ts',
    fileName: (className: string) => className,
  },
  extensions: [Migrator, SeedManager],
  findOneOrFailHandler: (entityName) => {
    throw new NotFoundException(`${entityName} not found`);
  },
});

export default config;
```
3) After defining the entities, we create a migration file using `pnpm run mikro-orm migration:create`; Migration file is successfully created.
4) We run the migration `pnpm run mikro-orm migration:up` we get the above error.

## Debugging

While debugging the node modules folder I had identified that there is **no function** for getting the namespaces in the file `project\node_modules\@mikro-orm\mssql\MsSqlSchemaHelper.js` like how it is there for the file `PostgreSqlSchemaHelper.js` under the `@mikro-orm/postgresql`.
If you have a look at the below file I have mentioned
`project\node_modules\@mikro-orm\migrations\MigrationStorage.js`
In the line 79, the variable schemas gets an empty value as an array for namespaces, causing the line 81 `knex.schema.createSchema()` to fail (CHECK THE STACK TRACE)

## Solution I had tried

I had tried this solution by pasting this code snippet into MsSqlSchemaHelper.js and I was able to run the migration successfully.
```js
    async getNamespaces(connection){
        return ['dbo'];
    }
```

image

Can you please help me out with this.

### What driver are you using?

@mikro-orm/mssql

### MikroORM version

6.2.8

### Node.js version

v20.11.0

### Operating system

Windows 11 23H2

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by HarihararamSriram**
This is linked with the issue closes #5633 

I have overriden the method `getNamespaces` inside the MSSqlSchemaHelper so that we can dynamically get the namespaces present in the MSSQL connection that was configured with the Mikroorm instance of the application.

I have tested this query with migration files that migrate the database up and I was able to successfully do that.
To be precise was able to run these commands successfully and the changes were reflected in the DB:

```sh
mikro-orm migration:create --initial
mikro-orm migration:create && mikro-orm migration:up
mikro-orm migration:down #If required to reduce the version of migration is also successful
```

Please let me know whether this looks good and I am up for any changes or refinements. Thank you

### CODE REVIEW

**Review by B4nan — APPROVED** [review]
looks like the method is used only when ensuring the migrations table exists (and it is set to be in a non default schema). i will test this myself a bit and fill the missing test. 

but next time please add the test yourself, tests are needed and your chances on a PR being merged without any added tests are usually very low, take this as an exception :]

**Comment by HarihararamSriram** [comment]
I have a query (sorry I am new to contributing here), so I should include test files for the coverage report to read 100% right?

**Comment by HarihararamSriram** [comment]
Sure @B4nan sorry, I will include it from next time it was an oversight from my side.

**Comment by B4nan** [comment]
Did some tests and you fixed it only partially, or better say, you fixed the happy path when the schema in question exists, but if its not, you end up with the same error, since again, knex does not support creating the schema at all.

**Comment by HarihararamSriram** [comment]
Got it @B4nan, thank you for the heads up :) 
So the sad path where the schema doesn't exist, will only work if knex releases support for creating the target schema in mssql too right? Or is there anything that I need to do additionally here.

**Comment by B4nan** [comment]
Fixed it via fe1be6f099888ad9e289f091d53428a4498f4b0d, its tiring how much inconsistencies there are in the different knex dialects, at some point I would like to get rid of knex completely for the internal parts since we already need to workaround so many things like this one, it already feels like it's adding more roadblocks than it solves.

**Pull request merged**
