### PR TITLE
Feature: Add $fulltext operator

### PR DESCRIPTION
**Pull request by thekevinbrown**
Add a $fulltext operator that can be used in queries on SQL databases. The syntax used varies per database and is not supported on MongoDB.

Closes: #620

### CODE REVIEW

**Comment by B4nan** [comment]
Nice! Target the `dev` branch please, I am not planning to release more features in v3.

**Comment by B4nan** [comment]
Btw mongo does support fulltext search too, via `$text`:

https://docs.mongodb.com/manual/text-search/

(will be happy to merge this without mongo support for sure, just a heads-up for future improvements)

**Comment by B4nan** [comment]
Do you plan to finalize this?

**Comment by thekevinbrown** [comment]
Yup, will probably get some time on this again next week.

**Comment by B4nan** [comment]
Btw I see this was based on `master`, we need it to be based on `dev`.

**Comment by thekevinbrown** [comment]
Yup, I’ll do it fresh based on dev when I’ve got the logging thing sorted. Will close this for now and open when it’s ready.

**Comment by B4nan** [comment]
Agreed, the logging/performance issue has definitely higher priority.

**Pull request closed without merging**
