### PR TITLE
feat(core): add `Collection.isEmpty()` method

### PR DESCRIPTION
**Pull request by rubiin**
Adds the isExists which returns either true false based on the collection count same as doctrine

### CODE REVIEW

**Comment by rubiin** [comment]
> let's at least mention the method in here
> 
> [mikro-orm.io/docs/collections](https://mikro-orm.io/docs/collections)
> 
> should be enough to include it in the code block, I hope I will find some time to rework this section a bit and explain the methods too

Must have missed it. I will update the pr

**Comment by rubiin** [comment]
https://github.com/mikro-orm/mikro-orm/issues/4592

**Comment by rubiin** [comment]
I have also implemented slice but don't know where I should add the tests. Is there a centralized file for collections test.

**Review by B4nan — APPROVED** [review]
thanks

**Comment by rubiin** [comment]
Thanks to you for such a great ORM :)

**Comment by B4nan** [comment]
Regarding the slice method, I'd like that to be a bit smarter than just converting all the items from `Set` to an array just to call `slice` on it - ideally just iterate on the `Set` and create a new array only from the items that should be there (and finish iterating once you reached the end of the range, not the whole `Set`).

I don't think we have any test suite for collections, feel free to create one in the `tests/features`, we could move other collection-related tests in there (out of the huge EM test suites, those are a bit legacy tests).

**Comment by rubiin** [comment]
Sure thing

**Comment by rubiin** [comment]
Onething we could do is , keep a counter and iterate over the set something like this but one gotcha will be we cant jump 
off to a particular index and always have to start from 0

```
let start = 0;

for (const element of set1) {
    start += 1;

    if (start === end) {
        break;
        '
    }

}


```

**Comment by rubiin** [comment]
on it. Seems like the same thing I have in mind

**Pull request merged**
