### PR TITLE
MikroORM v3

### PR DESCRIPTION
**Pull request by B4nan**
**Progress**
- [x] Change `autoFlush` default value to `false` #63
- [x] Use knex as query runner #64
- [x] Enable connection pooling #64
- [x] Rework schema generator to use knex #81
- [x] Remove deprecated 1:m `fk` parameter #87
- [x] Move `MetadataStorage.getClassName()` to `NamingStrategy` #15
- [x] Use instance of metadata instead of global storage #91
- [x] Add onInit lifecycle hook #83
- [x] Support virtual property getters #82
- [x] Support multiple conditions in JOINs #70
- [x] Add entity generator based on current db schema #78, #98 
- [x] Implement schema updates #97
- [x] Add basic CLI tool #101, #102
- [x] Improve logging - add namespaces, colors and highlighting #108, #109
- [x] Support for read replica connections #77, #116 
- [x] Add `Reference<T>` wrapper to allow better type checking of m:1 and 1:1 references #107, #117 
- [x] Add support for MariaDB #110, #120
- [x] Add `findOneOrFail` method to entity manager and repository #133, #142 
- [x] Add debug CLI command to ease debugging of ORM's configuration #136
- [x] Allow logging full query including params #155
- [x] Add type-safe way to define relationships #146
- [x] Validate one to one relationship metadata #149 
- [x] Auto-wire missing references from owner to inverse side #149 
- [x] Allow populating all relationships via passing `populate: true` #160 
- [x] Add `findAndCount()` to EM and repository interface #123 
- [x] Allow querying by relationships #157 
- [x] Add support for eager loading #168
- [x] Improve typing of FilterQuery #124, #193
- [x] Rework IEntity interface and entity definition #171, #193
- [x] Allow mapping results of query builder to entities directly
- [x] Add support for bundling via Webpack #196, #200
- [x] Allow using composite PK in M:N pivot tables #121, #204
- [x] Do not require `entity` attribute in collection decorators #207
- [x] Add support for migrations via umzug #209
- [x] Add migrations support to CLI #209
- [x] Add support for enums via `@Enum()` #215, #232 
- [x] Add support for create/drop database #237
- [x] Add `ReflectMetadataProvider` #240
- [ ] Add support for user defined indexes via `@Index()` #226
- [ ] Support searching by regexp in query builder

**Documentation**
- [x] autoFlush
- [x] new schema generator API
- [x] entity generator
- [x] CLI
- [x] virtual properties
- [x] new naming strategy api (`getClassName()`)
- [x] new logger configuration
- [x] `Reference<T>` wrapper
- [x] MariaDB driver
- [x] Read replica connections
- [x] Cross-database joins and cross-schema joins
- [x] Defining relationships
- [x] Upgrading v2 to v3 guide - `autoFlush`, knex, `fk` option, ...
- [x] Reworked entity definition
- [x] Deployment section
- [x] Migrations
- [x] Update example repositories, maybe split them to dedicated repos #131
- [x] Metadata providers
- [ ] Update roadmap

docs for v3 can be found here: https://mikro-orm.github.io/docs/v3/

upgrading guide: 
- up to date: https://github.com/mikro-orm/mikro-orm/blob/dev/docs/upgrading-v2-to-v3.md
- snapshot: https://mikro-orm.github.io/docs/v3/upgrading-v2-to-v3/

### CODE REVIEW

**Comment by Ty3uK** [comment]
@B4nan found weird issue in latest alpha:
When document modified outside (from Robo 3T) mikro-orm doesn't apply changed values to entity.

In [`findOne`](https://github.com/mikro-orm/mikro-orm/blob/master/lib/EntityManager.ts#L98) method we can pass `refresh` param to `merge`, maybe do similar thing inside [`find`](https://github.com/mikro-orm/mikro-orm/blob/master/lib/EntityManager.ts#L67) method?

I can create PR if you want :)

**Comment by B4nan** [comment]
> @B4nan found weird issue in latest alpha:
> When document modified outside (from Robo 3T) mikro-orm doesn't apply changed values to entity.
> 
> In [`findOne`](https://github.com/mikro-orm/mikro-orm/blob/master/lib/EntityManager.ts#L98) method we can pass `refresh` param to `merge`, maybe do similar thing inside [`find`](https://github.com/mikro-orm/mikro-orm/blob/master/lib/EntityManager.ts#L67) method?
> 
> I can create PR if you want :)

Well, that sound like you are not using request context? It is not supposed to refresh things in the background, but every request should have its own context which pretty much solves it (the refresh flag is there to allow overriding things that are already loaded in the context). Sure we can add the refresh flag to find options too, but the root cause will be elsewhere.

**Comment by Ty3uK** [comment]
@B4nan My bad, I'll check it out.
Thank you!

**Comment by lookfirst** [comment]
I think at some point soon, you should call it done and get it out there... future features can be added at later dates...

**Comment by B4nan** [comment]
Agreed, this has grown to a monster, I was planning to make it pretty small (mainly knex focused) release, but then you came in and reported/suggested so many things :P And then I wanted to add more and more to make it feature complete (e.g. migrations support felt like the last missing piece of puzzle)... 

I guess I will keep mongo transactions for some early 3.x release, I will definitely add the missing support for regexp/rlike in query builder, but then we can call it a go. 

I have also WIP of new website done with docusaurus I'd like to finish before the actual release, but that can come during RC period (after this is merged).

**Comment by lookfirst** [comment]
Yea, sorry about that. =) I know. =) I think most important must have for v3 is to have great docs.

**Comment by B4nan** [comment]
Regarding docs, do you see anything outstanding I should cover or improve? 

As part of the new website I will also add algolia search which should greatly improve the experience.

**Comment by lookfirst** [comment]
Not at this time. There is a lot of small "english as a second language" things like what I've changed in this PR ... but nothing major. You're doing great... =)

**Comment by B4nan** [comment]
Time has come, merged and released `3.0.0-rc`. 

Will keep it in RC till new website (docusaurus rewrite) and announcement article are ready. Hopefully stable release will be out early december.

**Pull request merged**
