### PR TITLE
docs: add a section on using MikroORM in NestJS with GraphQL

### PR DESCRIPTION
**Pull request by roderik**
Fixes: https://github.com/mikro-orm/nestjs/issues/22

### CODE REVIEW

**Comment by B4nan** [comment]
Looking good, can you please update the next docs too (in `docs/docs`)?

**Comment by roderik** [comment]
Done

**Review by B4nan — APPROVED** [review]
cc @Langstra we should update the nest PR with this too

**Comment by B4nan** [comment]
Thanks!

**Pull request merged**
