### PR TITLE
feat(core): add support for Node.js 14

### PR DESCRIPTION
**Pull request by Yaty**
here we go again :)

### CODE REVIEW

**Comment by B4nan** [comment]
Should be caused by node-postgres, it is supposed to be fixed in the latest patch version, can you try to upgrade it?

https://github.com/brianc/node-postgres/issues/2180

**Comment by B4nan** [comment]
You will need to update the lock file too I guess (by actually installing it via `yarn`)

**Comment by B4nan** [comment]
Already did the update in dev branch, so its enough to rebase this now.

**Comment by B4nan** [comment]
apparently there is one more issue with FileCacheAdapter:

```
TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (123)TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (123)
```

**Comment by Yaty** [comment]
alright it seems ok now, thanks for guidance :)

**Comment by B4nan** [comment]
Good, thank you! Let's make this feature commit so it gets to the changelog :]

**Pull request merged**
