### PR TITLE
fix: reproduction (#2410)

### PR DESCRIPTION
**Pull request by parisholley**

### CODE REVIEW

**Comment by parisholley** [comment]
interesting to note about this test:

a) if you move the code out of the transaction and flush at the end, it passes without issue
b) if you leave the code in the transaction, but remove `member.users.removeAll();`, it runs as well

**Comment by B4nan** [comment]
Would be good if you use sqlite for those reproductions that are not driver specific, so we can use in memory database that is much faster and does not require dropping/ensuring/etc.

This way it also passes just fine, which seems like how it would actually work in a real app:

```ts
    await orm.em.persistAndFlush(mu);
    orm.em.clear(); // <-- added clear to simulate new request

    await orm.em.transactional(async tx => {
      const member = await tx.findOne(MemberMikro, createdMember.id, {
        populate: ['ownedUsers', 'users'], // <-- populated users as the collection wouldn't be populated
      });

      if (member) {
        member.users.removeAll();
        tx.remove(member);
      }
    });
```

> b) if you leave the code in the transaction, but remove member.users.removeAll();, it runs as well

Yeah well, you are trying to be explicit about everything, and it can actually break things :D It also works fine if you first call `tx.remove(member)` and after that `member.users.removeAll()`. That `removeAll` call is kinda implicit due to the cascade delete enabled on the collection, maybe it's simply triggered twice if you do it this way.

The problem might be that the `tx.remove()` call cascades right ahead to the relation. Maybe we should let the cascading work only when flush is called, same way as persist works now.

**Comment by parisholley** [comment]
> Would be good if you use sqlite for those reproductions that are not driver specific, so we can use in memory database that is much faster and does not require dropping/ensuring/etc

sure

> This way it also passes just fine, which seems like how it would actually work in a real app:

correct, this was an issue i produced in a test, the code under test would have been split into two requests. nonetheless, i think it is important to address test-only issues because it may reveal an underlying problem that could affect other code-paths

> It also works fine if you first call tx.remove(member) and after that member.users.removeAll()

i don't think anyone would intuitively do that given that if you were to write the SQL, you'd remove users first

> That removeAll call is kinda implicit due to the cascade delete enabled on the collection, maybe it's simply triggered twice if you do it this way

Yeah, this is what i've figured. I just removed the `removeAll` calls to work around

> The problem might be that the tx.remove() call cascades right ahead to the relation

I think this is fine, because you'd want those collections to propagate (i assume that logic is intertwined). perhaps a `removeAll` should mark the entity (`member` in this case) that the `users` have already been cascaded, and simply skip over that in its cascading.

**Comment by B4nan** [comment]
The problem here is actually in the collection state, as its snapshot says it is empty, and that is the reason why the items are not cascaded. If you manally take the collection snapshot before opening the transaction, things work as expected. I believe this might be actually side effect of #2371 that is visible in the reproduction too on the `mu` entity. If I refactor to have a single `em.create()` and single `em.flush()` for the initial setup, the snapshot is taken properly:

```ts
    const mu = orm.em.create(MemberUser, {
      member: {},
      user: {},
    });
    const createdMember = mu.member.unwrap();
    await orm.em.persistAndFlush(mu);
```

**Pull request closed without merging**
