### PR TITLE
fix(core): define the primary key of the entity regardless of the hook in which it was defined

### PR DESCRIPTION
**Pull request by justkey007**
When registering a new entity, if the primary key is defined in the constructor or in the @BeforeCreate hook of the entity class, it returns an undefined value as an identifier to its related entities unless the primary key has been initialized through a function on the onCreate option of the PrimaryKey decorator.

```typescript
const publisher = new Publisher('Bastoz', PublisherType.GLOBAL);
const book = new Book('Le manguier', '1');
publisher.books.add(book);
```
Each entity inherits from the same base class which defines the primary key during the @BeforeCreate hook.

Here is the (incorrect) result obtained in debug mode:
```sql
INSERT INTO `publisher` (`created_at`, `id`, `name`, `owner_id`, `type`, `updated_at`)
VALUES ('2020-09-30 19:11:47.789', '5896064505599379', 'Bastoz', '1', 'global', NULL);


INSERT INTO `book` (`author_id`, `created_at`, `id`, `owner_id`, `publisher_id`, `title`, `updated_at`)
VALUES ('1', '2020-09-30 19:11:47.820', '8304010352419691', '1', NULL, 'Le manguier', NULL);

```

Normally expected result:
```sql
INSERT INTO `publisher` (`created_at`, `id`, `name`, `owner_id`, `type`, `updated_at`)
VALUES ('2020-09-30 19:11:47.789', '5896064505599379', 'Bastoz', '1', 'global', NULL);


INSERT INTO `book` (`author_id`, `created_at`, `id`, `owner_id`, `publisher_id`, `title`, `updated_at`)
VALUES ('1', '2020-09-30 19:11:47.820', '8304010352419691', '1', '5896064505599379', 'Le manguier', NULL);


```
After analyzing the source code I found the value of the identifier was not set if it was not set by the onCreate function of the Primarykey decorator option. Everything has been done better so as not to break the existing tests. Thank you!

### CODE REVIEW

**Comment by B4nan** [comment]
Add some tests please, the 100% (branch) coverage is mandatory, especially for changes in UoW/persistence internals. Maybe the place where you handled this is not the best one, I'd like to first see the (failing) test on my end to see what is actually happening. 

Not sure why have you skipped the `mapPrimaryKey` call altogether, the method handles custom types, and I would say it is needed. You might not break the existing tests, but only few entities in the tests are using custom types for PKs and none of them are assigning the PK value thru a hook... 

In general I would expect this to be handled somewhere else - where the hooks are processed (`UoW.runHooks()` method).

**Comment by justkey007** [comment]
> Not sure why have you skipped the `mapPrimaryKey` call altogether, the method handles custom types, and I would say it is needed. You might not break the existing tests, but only few entities in the tests are using custom types for PKs and none of them are assigning the PK value thru a hook...
> 
I tried it before but the tests are broken and I got around it

**Comment by justkey007** [comment]
> Add some tests please, the 100% (branch) coverage is mandatory, especially for changes in UoW/persistence internals. Maybe the place where you handled this is not the best one, I'd like to first see the (failing) test on my end to see what is actually happening.

I just created issue #893 with a related test that will allow you to better see what I'm talking about. Thank you

**Comment by B4nan** [comment]
Thanks for pointing this out. I picked a bit different way to fix this - by setting the identifier value based on the diff right after we execute the hook.

**Pull request closed without merging**
