### PR TITLE
fix: fixed github actions coverage

### PR DESCRIPTION
**Pull request by pepakriz**

### CODE REVIEW

**Comment by pepakriz** [comment]
@B4nan it failed again. So maybe wrong configuration on the coveralls.io side? I'd like to fix it because every PR is failing due to this issue.

**Comment by B4nan** [comment]
The problem is with gh actions not providing secrets when running against forks. Tried to fix this already by not running the coveralls request when the token is missing, but apparently its not working.

**Comment by pepakriz** [comment]
Wow, I've solved it. Take a look...

**Comment by B4nan** [comment]
Perfect, thanks!

**Pull request merged**
