### PR TITLE
fix(schema): always ignore PostGIS schemas when diffing

### PR DESCRIPTION
**Pull request by corbt**
As proposed in https://github.com/mikro-orm/mikro-orm/issues/386#issuecomment-1121065610

### CODE REVIEW

**Review by B4nan — APPROVED** [review]

**Review by B4nan — CHANGES_REQUESTED** [review]
needs updated snapshots, please run `yarn test -u` and commit the changes

**Comment by corbt** [comment]
Snapshots updated!

**Comment by B4nan** [comment]
one test is still failing

**Comment by B4nan** [comment]
thanks!

**Pull request merged**
