### PR TITLE
docs: fix wrongly named prop in polymorphic embed page

### PR DESCRIPTION
**Pull request by JonParton**
Looks like there was a typo after copy and pasting one of the examples from above!

Just scoping out the library and learning so sorry if I missed anything else!

### CODE REVIEW

**Review by B4nan — CHANGES_REQUESTED** [review]
thanks!

the decorator here also shoudnt be there

https://github.com/mikro-orm/mikro-orm/pull/4210/files#diff-583adf89d040146349c9f71612131f1f86e2170abd4400ad0abc47820f3c7632R693

and please update the next docs too, in the `docs/docs` folder

**Comment by JonParton** [comment]
Did think that was wrong as well but not knowing the library fully I wasn't 100% sure! 😂

I'll take a look when I get chance!

**Comment by JonParton** [comment]
Sorry I never got to this @B4nan!! 🙈

Thanks for correcting! 👍

**Comment by B4nan** [comment]
No worries, and thanks for reporting :)

**Pull request closed without merging**
