### PR TITLE
build: add Node.js 14

### PR DESCRIPTION
**Pull request by Yaty**
Node.js 14 is now available, I think it should be tested :)

### CODE REVIEW

**Comment by B4nan** [comment]
i would expect the CI to fail, let's see. a lot of dependencies are out of date because of node 8 support - in `dev` branch is v4 with up to date dependencies, so we could try that instead

**Comment by B4nan** [comment]
yes, failing as expected. please target the `dev` branch.

**Comment by B4nan** [comment]
You will need to base it on dev branch too (might be easier to create new MR).

**Comment by Yaty** [comment]
Yes I will do that

**Pull request closed without merging**
