### PR TITLE
add example with sqlite

### PR DESCRIPTION
**Pull request by lookfirst**

### CODE REVIEW

**Comment by B4nan** [comment]
is this really true? i thought the filename can be pretty much any filename, regardless its extension (i would expect it to allow also files without extensions)

**Comment by lookfirst** [comment]
when i had it without the suffix...

[Error: SQLITE_CANTOPEN: unable to open database file] {
  errno: 14,
  code: 'SQLITE_CANTOPEN'
}

**Comment by lookfirst** [comment]
try it in the little test project i just uploaded

**Comment by B4nan** [comment]
that sounds more like a permissions issue, will give it a try but it sounds really strange, especially when i was not able to find that in sqlite driver docs.

**Comment by lookfirst** [comment]
what permissions? i'm on an osx mac and running in my account. adding .db fixed the issue.

**Comment by B4nan** [comment]
I don't know what your error is about, but all tests are passing on my machine if I omit the extension or change it to something else (tried `.ext`).

**Comment by B4nan** [comment]
Tried your example project, and it fails with that error for database `test`, but `test123` works... Guess why - you already have something called `test` in your root directory - its the `test` directory :]

**Comment by lookfirst** [comment]
HAHAHAHAHAHAHA

**Pull request closed without merging**
