### PR TITLE
fix(cli): await the yargs.parse call in esm.ts

### PR DESCRIPTION
**Pull request by DASPRiD**
Related to https://github.com/mikro-orm/mikro-orm/issues/4265

https://github.com/mikro-orm/mikro-orm/commit/37574723d0ce37a8d0d3284124d836a517f451a7 did fix the call in `cli.ts` but forgot to update `esm.ts`.

### CODE REVIEW

**Review by B4nan — APPROVED** [review]
thanks!

**Comment by DASPRiD** [comment]
That was fast, the CI couldn't even finish validating ;)

**Comment by B4nan** [comment]
Well, the `cli.ts` and `esm.ts` are the only files that are not tested anyhow, so waiting for it isnt really worth it :D

**Comment by DASPRiD** [comment]
Haha good point. Remind me to get you a beer next time I'm close to your city :D

**Pull request merged**
