### PR TITLE
feat(core): add support for composite keys

### PR DESCRIPTION
**Pull request by B4nan**
Related #66

### CODE REVIEW

**Comment by darkbasic** [comment]
I'll give it a try, I'm pretty sure I will have to refactor my dataloading PR to support this.

**Comment by B4nan** [comment]
This is still WIP. Will send more changes and tests later today, with support for FK as PK, and basically for all what doctrine supports (as I am designing the tests based on their docs):

https://www.doctrine-project.org/projects/doctrine-orm/en/2.7/tutorials/composite-primary-keys.html

Not sure if I will also add support for having composite key entities as owners in relations, that might be a bit tricky... But I will give it a try too :]

**Comment by B4nan** [comment]
Quick progress report, support for composite entities in relationships is almost ready, I am aiming to release 3.5 later this week (it will take few more days for sure, but the hard parts are implemented already).

**Comment by B4nan** [comment]
Still need to do some code clean up, but pretty much all of the functionalities are now implemented. Will release this probably tomorrow.

**Pull request merged**
