### PR TITLE
fix: reproduction (#2406)

### PR DESCRIPTION
**Pull request by parisholley**

### CODE REVIEW

**Comment by parisholley** [comment]
https://github.com/mikro-orm/mikro-orm/blob/a5fb40f62cbddfd051aebf0c1f4b52e671e7d006/packages/core/src/entity/EntityFactory.ts#L142-L152

adding logic here to flip initialized = false, solves my issue, though it is protected and hard to say if this issue can occur other places

**Comment by B4nan** [comment]
Yes, that is the right place, and it should be fired only if newEntity flag is false.

**Comment by parisholley** [comment]
i'm also finding the same problem happens in reverse and is related to #2408

if you do new Entity(), the collections are initialed = true, if you do em.create() and DO NOT pass the collections as an empty array, initialized = false and similar problems occur

**Comment by parisholley** [comment]
> Yes, that is the right place, and it should be fired only if newEntity flag is false.

you comfortable with a ts-ignore or is there a better way to do this?

**Comment by parisholley** [comment]
https://github.com/mikro-orm/mikro-orm/blob/a5fb40f62cbddfd051aebf0c1f4b52e671e7d006/packages/core/src/EntityManager.ts#L513-L515

believe this PR would need the inverse here, loop through collections, always set initialized = true

**Comment by B4nan** [comment]
> if you do new Entity(), the collections are initialed = true, if you do em.create() and DO NOT pass the collections as an empty array, initialized = false and similar problems occur

That needs to be addressed here, as with the flag the value is there:

https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/hydration/ObjectHydrator.ts#L177

**Comment by B4nan** [comment]
> you comfortable with a ts-ignore or is there a better way to do this?

Can't say I like it, but it's not a big deal.

**Comment by B4nan** [comment]
Actually even better way to make the behaviour same is just deleting the collections and let the hydrator create new instances, when it's not a new entity. This way it will be closer to how it works without forcing the constructor usage.

**Pull request closed without merging**
